export { ReactComponent as AzureIcon } from './azure.svg'
export { ReactComponent as AWSIcon } from './aws.svg'
export { ReactComponent as CisIcon } from './cis.svg'
export { ReactComponent as HipaaIcon } from './hipaa.svg'
export { ReactComponent as KaytuIcon } from './logo-mini.svg'
